### ISSUE TITLE
Add new countries to drop down on SPSS LP

### ISSUE THREAD

**Issue by hulank** [kivuto/lp-spss#4]
SPSS landing page:

Ops will be updating the country eligibility of SPSS around October 10th. I have asked them to give us a heads up before they do. 

Here are the new countries that need to be added into the list of countries on the eligibility drop down. Please add them in alphabetically.

Austria, Belgium, Cyprus, Estonia, Finland, Greece, Ireland, Italy, Latvia, Malta, Portugal, Slovakia, Slovenia, Sweden

I'll update you when I get a launch time!

**Comment by jburcsik** [comment]
I assume this is closed?

**Comment by hulank** [comment]
Yes can be closed
